language: python
cache: pip
sudo: false
env:
  global:
  - PACKAGENAME="ppong"
  - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
python:
- 3.6
before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- echo $MINICONDA_URL
- wget $MINICONDA_URL -O miniconda.sh;
- bash miniconda.sh -b -f -p $MINICONDA;
- conda config --set always_yes yes
- conda update conda
- conda info -a
install:
- python setup.py install --record installed_files.txt
script:
- python test/test_install.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: rraadd88
  distributions: sdist bdist_wheel
  password:
    secure: uFweRTvCDDZ8WQ3SJmn9x6AyXLl49RnkCtH4r+NgKNuEVIIWmQNkY/sUKgV/EX+jRXlRXxO2SJznOLiJR7H5uS5gE3BzRihEcOUk+7F0zYSFs04l3+Ykx+sFb5Ov2dD10UuxHYwjjHg4WS/rD/8ll43VIm7HG9KGg/Xx8yoltQOl0986X6+DAvoZf8j5xIE/stXl14QydUJS8XBXCbbqEa3YYHiw37DxH5fADTWyvn+xFdC0ukFH8rZnPoYYUNlUk+m/FwBBJwlmfrZeue1byT+MCjMRPHZJA80xhvYOEEhi0rSEtj+eBoAjtaeiXHOHgtJHEFA7TYvhtLoCQ4Bi9p3fuI7PtTWtB74tjXI/R1eXzLWDNILC4n+KRAGXVNmmkmcXvf6/u6x8OPOqy3ocUJCLV/B2nuc+S2xSS8Rl9/pLZSg6Sk6L2D4p2yVXVF95hh5poj9He9gXvqLgEsL6EaDN9SOt7ZaCpRN6hC8Yvaxos8G6n6M+sCHfYs8FZladu7mgF+hrVF/ZQcN0UnQMV2eYtXXZX4q14OP6Yobn3VyEM+XwvGsDl96fGL8epT6lYAl3yFfYBztYDxMXlTOzRhPQXFFaI2I8VEk2bc6nrAw27szQkzjT8yudUH6eG144znokdEEj7T4ses85OCsKadRLKPVRbvsKe411mBs51NM=
  true:
    tags: true
    branch: master